// Power-aware Immediate Generator
// Based on the custom ISA field layout:
//
// I-Type : FUNC[31:27] | IMM[26:15] | RS1[14:10] | RD[9:5] | OPCODE[4:0]
// S-Type : FUNC[31:27] | IMM[26:15] | RS1[14:10] | RD[9:5] | OPCODE[4:0]
// B-Type : FUNC[31:27] | IMM[26:15] | RS1[14:10] | RD[9:5] | OPCODE[4:0]
// J-Type : IMM[31:10]  | RD[9:5]     | OPCODE[4:0]

module immext #(
    parameter Width = 32
)(
    input  [31:0] instruction,

    // Generated by decoder
    input         ImmEnable,

    // 000 = NONE
    // 001 = I-Type
    // 010 = S-Type
    // 011 = B-Type
    // 100 = J-Type
    input  [2:0]   ImmType,

    // 00 = Sign extend
    // 01 = Zero extend
    // 10 = Shifted sign extend
    // 11 = Custom pattern
    input  [1:0]   ImmMode,

    output reg [Width-1:0] Out
);

    // =========================================================
    // INPUT ISOLATION
    // =========================================================

    wire [31:0] instruction_iso;
    wire [2:0]  ImmType_iso;
    wire [1:0]  ImmMode_iso;

    assign instruction_iso = ImmEnable ? instruction : 32'b0;
    assign ImmType_iso     = ImmEnable ? ImmType : 3'b000;
    assign ImmMode_iso     = ImmEnable ? ImmMode : 2'b00;


    // =========================================================
    // IMMEDIATE GENERATION
    // =========================================================

    always @(*) begin

        // Default
        Out = {Width{1'b0}};

        case (ImmType_iso)

            // =================================================
            // I-TYPE
            // IMM = instruction[26:15]
            // =================================================

            3'b001: begin

                case (ImmMode_iso)

                    // Sign extend
                    2'b00:
                        Out = {
                            {(Width-12){instruction_iso[26]}},
                            instruction_iso[26:15]
                        };

                    // Zero extend
                    2'b01:
                        Out = {
                            {(Width-12){1'b0}},
                            instruction_iso[26:15]
                        };

                    // Sign extend then shift left by 2
                    2'b10:
                        Out = (
                            {
                                {(Width-12){instruction_iso[26]}},
                                instruction_iso[26:15]
                            }
                        ) << 2;

                    // Custom pattern
                    2'b11:
                        Out = {
                            16'hABCD,
                            instruction_iso[26:15]
                        };

                    default:
                        Out = {Width{1'b0}};

                endcase

            end


            // =================================================
            // S-TYPE
            // IMM = instruction[26:15]
            // =================================================

            3'b010: begin

                case (ImmMode_iso)

                    // Sign extend
                    2'b00:
                        Out = {
                            {(Width-12){instruction_iso[26]}},
                            instruction_iso[26:15]
                        };

                    // Zero extend
                    2'b01:
                        Out = {
                            {(Width-12){1'b0}},
                            instruction_iso[26:15]
                        };

                    // Sign extend then shift left by 2
                    2'b10:
                        Out = (
                            {
                                {(Width-12){instruction_iso[26]}},
                                instruction_iso[26:15]
                            }
                        ) << 2;

                    // Custom pattern
                    2'b11:
                        Out = {
                            16'hABCD,
                            instruction_iso[26:15]
                        };

                    default:
                        Out = {Width{1'b0}};

                endcase

            end


            // =================================================
            // B-TYPE
            // IMM = instruction[26:15]
            // =================================================

            3'b011: begin

                case (ImmMode_iso)

                    // Sign extend
                    2'b00:
                        Out = {
                            {(Width-12){instruction_iso[26]}},
                            instruction_iso[26:15]
                        };

                    // Zero extend
                    2'b01:
                        Out = {
                            {(Width-12){1'b0}},
                            instruction_iso[26:15]
                        };

                    // Sign extend then shift left by 1
                    2'b10:
                        Out = (
                            {
                                {(Width-12){instruction_iso[26]}},
                                instruction_iso[26:15]
                            }
                        ) << 1;

                    // Custom pattern
                    2'b11:
                        Out = {
                            16'hABCD,
                            instruction_iso[26:15]
                        };

                    default:
                        Out = {Width{1'b0}};

                endcase

            end


            // =================================================
            // J-TYPE
            // IMM = instruction[31:10]
            // 22-bit signed immediate
            // =================================================

            3'b100: begin

                case (ImmMode_iso)

                    // Sign extend 22-bit immediate
                    2'b00:
                        Out = {
                            {(Width-22){instruction_iso[31]}},
                            instruction_iso[31:10]
                        };

                    // Zero extend
                    2'b01:
                        Out = {
                            {(Width-22){1'b0}},
                            instruction_iso[31:10]
                        };

                    // Sign extend then shift left by 1
                    2'b10:
                        Out = (
                            {
                                {(Width-22){instruction_iso[31]}},
                                instruction_iso[31:10]
                            }
                        ) << 1;

                    // Custom pattern
                    2'b11:
                        Out = {
                            10'h2AA,
                            instruction_iso[31:10]
                        };

                    default:
                        Out = {Width{1'b0}};

                endcase

            end


            // =================================================
            // NONE / INVALID
            // =================================================

            default:
                Out = {Width{1'b0}};

        endcase

    end

endmodule